version: "2.3"
services:
  slackbot:
    image: golang:stretch
    ports:
      - 8080:8080
    working_dir: /go/src/slackbot-go
    entrypoint: go
    command:
      - run
      - slackbot-go
    volumes:
      - ./:/go/src/slackbot-go
